version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: $DOCKER_REPO_URL/circleci-jdk8:latest


    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and Publish Docker Image
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]]; then
              image_name=swagger-codegen-cli

              docker build -t $DOCKER_REPO_URL/$image_name:$CIRCLE_SHA1 .
              docker tag $DOCKER_REPO_URL/$image_name:$CIRCLE_SHA1 $DOCKER_REPO_URL/$image_name:latest

              $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
              docker push $DOCKER_REPO_URL/$image_name
            else
              echo "Skipping... not on master branch"
            fi

workflows:
  version: 2
  next-platform-pipeline:
    jobs:
      - build:
          context: next-platform-build
